server:
  port: 8080

spring:
  application:
    name: product-service
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      auto-commit: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:phw;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    lazy-initialization: false